Repository lblod/app-digitaal-loket, pull requests merged in 2023-02, with the labels that each got.

#320 Add a "review-status" relationship to the public services resource
  config/migrations/2023/20230116120500-add-status-concepts.graph
  config/migrations/2023/20230116120500-add-status-concepts.ttl
  config/resources/lpdc.json
Labels: enhancement

#333 [Toezicht Module] - APB - Fix form RPR
  config/migrations/2023/20230126155111-add-new-forms/20230126155111-add-file-resource.sparql
  config/semantic-forms/20230126155111-forms.ttl
  docker-compose.yml
Labels: bug

#336 Fix family name for Moerbeke Burgemeester
  config/migrations/2023/20230130170113-adjust-familienaam-burgemeester.sparql
Labels: data-fix
