Repository lblod/app-digitaal-loket, pull requests merged in 2023-10, with the labels that each got.

#466 Add BestuurInTijd and its start and end dates
  config/reports/worship/bedienaren.js
  config/reports/worship/mandatarissen.js
Labels: enhancement

#465 Rewrite reports worship with RDF libraries
  config/delta-producer/subsidies/export.json
  config/dispatcher/dispatcher.ex
  config/reports/worship/bedienaren.js
  config/reports/worship/mandatarissen.js
  config/reports/worship/namespaces.js
  config/reports/worship/queries.js
  config/reports/worship/temp-deletes.js
  config/reports/worship/temp-inserts.js
  config/reports/worship/utils.js
  config/resources/master-files-domain.lisp
  docker-compose.yml
Labels: bug, enhancement

#464 Add status to worship mandates producer
  config/delta-producer/worship-services-sensitive/export.json
Labels: data-fix

#471 Adding worship publication flag to existing ROs submissions
  config/migrations/2023/20231023101111-flag-concepts.sparql
  config/migrations/2023/20231023101143-flag-for-ro-submissions.sparql
  config/migrations/2023/20231023101303-flag-for-ro-submissions-attachements.sparql
  config/migrations/2023/20231023133318-flag-for-ro-submissions.sparql
Labels: data-fix
