Repository lblod/app-digitaal-loket, pull requests merged in 2025-02, with the labels that each got.

#630 Simplify vendor data
  CHANGELOG.md
  config/migrations/2025/20250124124100-flush-excess-vendor-data/20250124124200-flush-submission-document.sparql
  config/migrations/2025/20250124124100-flush-excess-vendor-data/20250124124201-flush-formdata.sparql
  config/migrations/2025/20250124124100-flush-excess-vendor-data/20250124124202-flush-artikel.sparql
  config/vendor-data/subjectsAndPaths.js
Labels: enhancement

#631 Remove submissions export config replaced by op sync
  config/export/submissions/type-export.js
Labels: enhancement

#632 Re-export missing submissions
  CHANGELOG.md
  config/migrations-publication-triplestore/2025/20250129150000-remove-submission-to-re-export.sparql
  config/migrations-publication-triplestore/2025/20250129150001-remove-submission-to-re-export.sparql
  config/migrations-publication-triplestore/2025/20250129150002-remove-submission-to-re-export.sparql
  config/migrations-publication-triplestore/2025/20250129150003-remove-submission-to-re-export.sparql
  config/migrations-publication-triplestore/2025/20250129150004-remove-submission-to-re-export.sparql
  config/migrations-publication-triplestore/2025/20250129150005-remove-submission-to-re-export.sparql
  config/migrations-publication-triplestore/2025/20250129150006-remove-submission-to-re-export.sparql
  config/migrations-publication-triplestore/README.md
  docker-compose.dev.yml
  docker-compose.yml
Labels: bug

#637 Remove 3 broken EredienstMandatarissen
  CHANGELOG.md
  config/migrations/2025/20250207040000-remove-3-broken-madates-willibrordus-neerpelt.sparql
Labels: data-fix

#636 Repair cross referencing submissions from CKBs without vendor
  CHANGELOG.md
  config/migrations/2025/20250205180000-repair-ckb-submissions-cross-refs-no-vendor.sparql
Labels: enhancement

#640 Remove 2 submission Beveren fusie
  CHANGELOG.md
  config/migrations/2025/20250210103100-remove-beveren-submission-for-resubmit-fusie/20250210103100-remove-beveren-submission-for-resubmit-fusie.sparql
  config/migrations/2025/20250210103100-remove-beveren-submission-for-resubmit-fusie/20250210103101-remove-beveren-submission-for-resubmit-fusie.sparql
Labels: data-fix

#643 Feature: show kbo number in dropdowns
  CHANGELOG.md
  docker-compose.yml
Labels: enhancement

#642 Remove fusiegemeenten for mock-login healing
  CHANGELOG.md
  config/migrations/2025/mocklogin/20250214032300-remove-old-gemeentes-for-fusie.sparql
Labels: data-fix
